// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4AWP6gSYkZuhpF8qreEzVDGyspfoNjeo',
    appId: '1:82926148600:web:dae244ef4dc46ab82a940d',
    messagingSenderId: '82926148600',
    projectId: 'food-app-6f1f3',
    authDomain: 'food-app-6f1f3.firebaseapp.com',
    storageBucket: 'food-app-6f1f3.appspot.com',
    measurementId: 'G-3WWXBG9469',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBonya3KzsBGSsbbyfSatVOyJ1e0xefeCw',
    appId: '1:82926148600:android:52286e936cc150352a940d',
    messagingSenderId: '82926148600',
    projectId: 'food-app-6f1f3',
    storageBucket: 'food-app-6f1f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDox_kLhSyucFnuacZvuqL9TnJPslxMXEw',
    appId: '1:82926148600:ios:94d7c187dc0f293c2a940d',
    messagingSenderId: '82926148600',
    projectId: 'food-app-6f1f3',
    storageBucket: 'food-app-6f1f3.appspot.com',
    iosBundleId: 'com.example.foodAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDox_kLhSyucFnuacZvuqL9TnJPslxMXEw',
    appId: '1:82926148600:ios:6404ece04ef5107f2a940d',
    messagingSenderId: '82926148600',
    projectId: 'food-app-6f1f3',
    storageBucket: 'food-app-6f1f3.appspot.com',
    iosBundleId: 'com.example.foodAdmin.RunnerTests',
  );
}
